### ISSUE TITLE
Scheduler is running but not tracking changes  

### ISSUE THREAD

**Issue by dadof3sods** [ddurdle/Python-GoogleDrive-VideoStream#92]
I have the scheduler set to run every 120 minutes, it has completed the initial run and created all the relevant strm files however leaving it running it shows that it is running but not seeing the changes in my media folder . folder=Media every 120 mins looking for changes -- last run status: 2018-09-01 06:57:18.981323 - Created 0 STRM file(s). (changetoken = 1474698) I know this is inaccurate because season 2 of a show was added overnight. 
This happens regularly sometimes restarting it kicks it off again however not always. Any ideas?

**Comment by ddurdle** [comment]
There is some kind of issue with the latest github.  Use the version in the releases folder 0.1.27

**Comment by dadof3sods** [comment]
ok have moved back to 0.1.27 and am having very similar performance. job #0 username=server folder=Media every 120 mins looking for changes -- running. it has been saying that continually for over 24 hours and no changes have been tracked.
any other ideas i can try?

**Comment by ddurdle** [comment]
Looks like it became stuck.  Try resetting the job status (+ reset job) and then restart the plugin so that it runs.

**Comment by dadof3sods** [comment]
Thanks for the tip, that got it running again.....but all of the changes have been put in a separate folder. my main media folder is structured as Media/TV,Movies etc now i have another Media folder inside the top level Media folder so now i have Media/Media/TV,Movies etc, that contain the changes since it last run. Is this expected behaviour? or did i bodge something up?

**Comment by HptmHavoc** [comment]
I am experiencing the same behavior when 'full sync then ongoing tracking' is enabled. On the first initial run, for example 'strm/Movies' is created. But subsequent new strms will get created in 'strm/Movies/Movies'. 

I don't know whether it behaves the same if 

catalog STRMs into folders according to movie/tv/other? **true**
when catalog STRMs=true, retain folder structure? **false**

is set.

**Comment by ddurdle** [comment]
When you set catalog = true, what is the folder you provide for the scheduled job?

If, for instance, I provide "/u01/shared/chris", it would create these subfolders as part of the classification (as lower case).
movies  music  tv  video-other

Is it TV and Movies with that casing?  Are those names on the google drive?

**Comment by ddurdle** [comment]
The original issue noted about the 0 STRM files should be fixed now in the latest github

**Comment by HptmHavoc** [comment]
Just for clarification, the behavior i described happens with catalog = false or catalog = true but retain folder structure = true. The _Movie_ folder i refer to exists actually on the google drive. 
So i provide a folder called **'Movie'** for the scheduler.

**Comment by mrmachine** [comment]
I'm also seeing my scheduled task not picking up changes (a 720p file was replaced with a 1080p file, but only the 720p strm file remains). I'm using catalog=false and my folder structure is `tv/show/seasonN/episode.mkv`

**Comment by sameerfattal** [comment]
> I am experiencing the same behavior when 'full sync then ongoing tracking' is enabled. On the first initial run, for example 'strm/Movies' is created. But subsequent new strms will get created in 'strm/Movies/Movies'.
> 
> I don't know whether it behaves the same if
> 
> catalog STRMs into folders according to movie/tv/other? **true**
> when catalog STRMs=true, retain folder structure? **false**
> 
> is set.

Having the same issue

**Comment by motas** [comment]
Still having the same issue.

Let's say I have this file structure on Google Drive:
**/HomeVideo/VideoA/VideoA.mp4
/HomeVideo/VideoB/VideoB.mp4**

and I create a scheduled task on the **HomeVideo** folder with the following settings:
Type of job : **full sync and ongoing tracking**
Location to store STRMs : **/home/Sync**
Catalog : **False**.

The initial run would create this folder structure:
**/home/Sync/HomeVideo/VideoA/VideoA.strm
/home/Sync/HomeVideo/VideoB/VideoB.strm**
which I assume is the normal behavior.

But if I upload a new video to Google Drive at 
**/HomeVideo/VideoC/VideoC.mp4**,
the tracking task would create the new strm file at 
**/home/Sync/HomeVideo/HomeVideo/VideoC/VideoC.strm**
instead of
**/home/Sync/HomeVideo/VideoC/VideoC.strm**.
